#!/usr/bin/env python3
"""Generate synthesizable opcode decode facts from validated specifications."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[1]
OPCODE_DIR = ROOT / "spec" / "opcodes"
OUTPUT = ROOT / "rtl" / "generated" / "m680x_decode_pkg.sv"
ARCHITECTURES = ("m6800", "m6801", "hd6301", "m6805", "hd6305")
ACCUMULATOR_BASES = {
    "SUB", "CMP", "SBC", "AND", "BIT", "LDA", "STA", "EOR", "ADC", "ORA", "ADD",
    "NEG", "COM", "LSR", "ROR", "ASR", "ASL", "ROL", "DEC", "INC", "TST", "CLR",
}
MODES = {
    None: "AM_NONE",
    "inherent": "AM_INHERENT",
    "relative": "AM_RELATIVE",
    "accumulator-a": "AM_ACCUMULATOR_A",
    "accumulator-b": "AM_ACCUMULATOR_B",
    "index-register-x": "AM_INDEX_REGISTER_X",
    "immediate-8": "AM_IMMEDIATE_8",
    "immediate-16": "AM_IMMEDIATE_16",
    "direct": "AM_DIRECT",
    "indexed-unsigned-8": "AM_INDEXED_8",
    "indexed-unsigned-16": "AM_INDEXED_16",
    "indexed-no-offset": "AM_INDEXED_NONE",
    "extended": "AM_EXTENDED",
    "bit-test-branch-direct": "AM_BIT_TEST_BRANCH",
    "bit-set-clear-direct": "AM_BIT_SET_CLEAR",
}


def _load(architecture: str) -> dict:
    path = OPCODE_DIR / f"{architecture}.json"
    spec = json.loads(path.read_text(encoding="utf-8"))
    if spec.get("architecture") != architecture or len(spec.get("opcodes", [])) != 256:
        raise ValueError(f"invalid opcode specification {path}")
    return spec


def _operation(record: dict) -> tuple[str, str, int]:
    mnemonic = record["mnemonic"]
    target = "TARGET_NONE"
    bit_index = 0
    if mnemonic.startswith(("BRSET", "BRCLR", "BSET", "BCLR")) and mnemonic[-1].isdigit():
        bit_index = int(mnemonic[-1])
        mnemonic = mnemonic[:-1]
    elif mnemonic[-1:] in {"A", "B", "X"} and mnemonic[:-1] in ACCUMULATOR_BASES:
        target = {"A": "TARGET_A", "B": "TARGET_B", "X": "TARGET_X"}[mnemonic[-1]]
        mnemonic = mnemonic[:-1]
    return f"OP_{mnemonic}", target, bit_index


def render() -> str:
    specs = {architecture: _load(architecture) for architecture in ARCHITECTURES}
    operation_names = ["OP_INVALID"]
    for architecture in ARCHITECTURES:
        for record in specs[architecture]["opcodes"]:
            if record["classification"] == "documented_instruction":
                operation_names.append(_operation(record)[0])
    operation_names = list(dict.fromkeys(operation_names))
    lines = [
        "// SPDX-License-Identifier: MIT",
        "// Generated by tools/build_rtl_decode.py; do not edit by hand.",
        "package m680x_decode_pkg;",
        "  typedef enum logic [3:0] {",
    ]
    mode_names = list(dict.fromkeys(MODES.values()))
    for index, name in enumerate(mode_names):
        comma = "," if index != len(mode_names) - 1 else ""
        lines.append(f"    {name} = 4'd{index}{comma}")
    lines += [
        "  } address_mode_t;",
        "",
        "  typedef enum logic [1:0] {",
        "    TARGET_NONE = 2'd0,",
        "    TARGET_A = 2'd1,",
        "    TARGET_B = 2'd2,",
        "    TARGET_X = 2'd3",
        "  } operation_target_t;",
        "",
        f"  typedef enum logic [{max(1, (len(operation_names) - 1).bit_length()) - 1}:0] {{",
    ]
    operation_width = max(1, (len(operation_names) - 1).bit_length())
    for index, name in enumerate(operation_names):
        comma = "," if index != len(operation_names) - 1 else ""
        lines.append(f"    {name} = {operation_width}'d{index}{comma}")
    lines += [
        "  } operation_t;",
        "",
        "  typedef struct packed {",
        "    logic          valid;",
        "    address_mode_t mode;",
        "    operation_t    operation;",
        "    operation_target_t target;",
        "    logic [2:0]    bit_index;",
        "    logic [1:0]    length;",
        "    logic [3:0]    cycles;",
        "  } opcode_decode_t;",
        "",
    ]
    for architecture in ARCHITECTURES:
        spec = specs[architecture]
        function_name = f"decode_{architecture}"
        lines += [
            f"  function automatic opcode_decode_t {function_name}(input logic [7:0] opcode);",
            "    begin",
            f"      {function_name} = '{{valid: 1'b0, mode: AM_NONE, operation: OP_INVALID, "
            "target: TARGET_NONE, bit_index: 3'd0, length: 2'd0, cycles: 4'd0};",
            "      case (opcode)",
        ]
        for record in spec["opcodes"]:
            if record["classification"] != "documented_instruction":
                continue
            mode = MODES[record["addressing_mode"]]
            operation, target, bit_index = _operation(record)
            lines.append(
                f"        8'h{record['opcode_hex'].lower()}: {function_name} = "
                f"'{{valid: 1'b1, mode: {mode}, operation: {operation}, target: {target}, "
                f"bit_index: 3'd{bit_index}, length: 2'd{record['length']}, "
                f"cycles: 4'd{record['cycles']}}};"
            )
        lines += [
            "        default: ;",
            "      endcase",
            "    end",
            "  endfunction",
            "",
        ]
    lines += ["endpackage", ""]
    return "\n".join(lines)


def write(check: bool) -> bool:
    expected = render()
    if check:
        try:
            actual = OUTPUT.read_text(encoding="utf-8")
        except OSError:
            actual = ""
        if actual != expected:
            print(f"generated RTL decode is stale: {OUTPUT}", file=sys.stderr)
            return False
        return True
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=OUTPUT.parent, delete=False) as output:
        output.write(expected)
        temporary = Path(output.name)
    temporary.replace(OUTPUT)
    print(f"wrote {OUTPUT}")
    return True


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    return 0 if write(parse_args(argv).check) else 1


if __name__ == "__main__":
    raise SystemExit(main())
