#!/usr/bin/env python3
"""Generate independent-model expectations for every documented M6800 opcode."""

from __future__ import annotations

import argparse
from pathlib import Path

from model.common import Memory
from model.m6800 import FLAG_BITS, M6800Model, M6800State


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "sim" / "generated" / "m6800_opcode_vectors_pkg.sv"
TARGET_PC = 0x100D


def fixture(opcode: int) -> M6800Model:
    memory = Memory()
    memory.load(TARGET_PC, [opcode, 0x10, 0x20, 0x30])
    for address in (0x0010, 0x0011, 0x0020, 0x0021, 0x1020, 0x1021, 0x2010, 0x2011):
        memory[address] = (address ^ 0x53) & 0xFF
    memory.load(0xFFFA, [0x30, 0x00, 0x31, 0x00, 0x32, 0x00])
    for offset, value in enumerate((0xC0, 0x34, 0x12, 0x20, 0x00, 0x10, 0x11), start=1):
        memory[0x4000 + offset] = value
    state = M6800State(a=0x12, b=0x34, x=0x2000, sp=0x4000, pc=TARGET_PC, ccr=0)
    return M6800Model("m6800", memory=memory, state=state)


def render() -> str:
    template = M6800Model("m6800")
    vectors: list[tuple[dict, M6800Model, object]] = []
    for record in template.spec["opcodes"]:
        if record["classification"] != "documented_instruction":
            continue
        model = fixture(record["opcode"])
        trace = model.step()
        vectors.append((record, model, trace))

    lines = [
        "// SPDX-License-Identifier: MIT",
        "// Generated by tools/build_m6800_rtl_vectors.py; do not edit by hand.",
        "package m6800_opcode_vectors_pkg;",
        f"  localparam int unsigned M6800_VECTOR_COUNT = {len(vectors)};",
        "  typedef struct packed {",
        "    logic [7:0] opcode;",
        "    logic [3:0] cycles;",
        "    logic [7:0] a;",
        "    logic [7:0] b;",
        "    logic [15:0] x;",
        "    logic [15:0] sp;",
        "    logic [15:0] pc;",
        "    logic [5:0] ccr;",
        "    logic [5:0] ccr_mask;",
        "    logic waiting_state;",
        "    logic [3:0] access_count;",
        "  } m6800_vector_t;",
        "  typedef struct packed {",
        "    logic write_enable;",
        "    logic [15:0] address;",
        "    logic [7:0] data;",
        "  } m6800_access_t;",
        "",
        "  function automatic m6800_vector_t m6800_vector(input int unsigned vector_index);",
        "    begin",
        "      m6800_vector = '0;",
        "      case (vector_index)",
    ]
    for index, (record, model, trace) in enumerate(vectors):
        undefined_mask = 0
        for flag in record["flags_undefined"]:
            undefined_mask |= 1 << FLAG_BITS[flag]
        ccr_mask = 0x3F & ~undefined_mask
        state = model.state
        lines.extend(
            [
                f"        {index}: begin // {record['opcode_hex']} {record['mnemonic']}",
                f"          m6800_vector.opcode = 8'h{record['opcode']:02x};",
                f"          m6800_vector.cycles = 4'd{record['cycles']};",
                f"          m6800_vector.a = 8'h{state.a:02x};",
                f"          m6800_vector.b = 8'h{state.b:02x};",
                f"          m6800_vector.x = 16'h{state.x:04x};",
                f"          m6800_vector.sp = 16'h{state.sp:04x};",
                f"          m6800_vector.pc = 16'h{state.pc:04x};",
                f"          m6800_vector.ccr = 6'h{state.ccr:02x};",
                f"          m6800_vector.ccr_mask = 6'h{ccr_mask:02x};",
                f"          m6800_vector.waiting_state = 1'b{int(state.waiting)};",
                f"          m6800_vector.access_count = 4'd{len(trace.accesses)};",
                "        end",
            ]
        )
    lines.extend(
        [
            "        default: ;",
            "      endcase",
            "    end",
            "  endfunction",
            "",
            "  function automatic m6800_access_t m6800_access(",
            "    input logic [7:0] vector_index,",
            "    input logic [7:0] access_index",
            "  );",
            "    begin",
            "      m6800_access = '0;",
            "      case ({vector_index[7:0], access_index[7:0]})",
        ]
    )
    for vector_index, (_record, _model, trace) in enumerate(vectors):
        for access_index, access in enumerate(trace.accesses):
            lines.extend(
                [
                    f"        16'h{vector_index:02x}{access_index:02x}: begin",
                    f"          m6800_access.write_enable = 1'b{int(access.kind == 'write')};",
                    f"          m6800_access.address = 16'h{access.address:04x};",
                    f"          m6800_access.data = 8'h{access.data:02x};",
                    "        end",
                ]
            )
    lines.extend(
        [
            "        default: ;",
            "      endcase",
            "    end",
            "  endfunction",
            "endpackage",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the committed artifact is stale")
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"stale generated RTL vectors: run {Path(__file__).name}")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(generated, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
