#!/usr/bin/env python3
"""Generate package-flattened core views for Yosys's Verilog frontend."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[1]
PACKAGE_PATHS = (
    ROOT / "rtl" / "common" / "m680x_alu_pkg.sv",
    ROOT / "rtl" / "generated" / "m680x_decode_pkg.sv",
)
CORES = {
    ROOT / "rtl" / "m6800" / "m6800_core.sv": ROOT / "rtl" / "generated" / "yosys_m6800_core.sv",
    ROOT / "rtl" / "m6805" / "m6805_core.sv": ROOT / "rtl" / "generated" / "yosys_m6805_core.sv",
}


def package_body(path: Path) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()
    package_index = next(index for index, line in enumerate(lines) if line.startswith("package "))
    end_index = next(index for index, line in enumerate(lines) if line == "endpackage")
    return "\n".join(lines[package_index + 1 : end_index]).strip("\n")


def render(core_path: Path) -> str:
    source = core_path.read_text(encoding="utf-8")
    source = "\n".join(
        line for line in source.splitlines()
        if not line.strip().startswith("import m680x_")
        and line.strip() != "// SPDX-License-Identifier: MIT"
    ) + "\n"
    header, separator, rest = source.partition(");\n")
    if not separator:
        raise ValueError(f"could not locate module port terminator in {core_path}")
    bodies = "\n".join(package_body(path) for path in PACKAGE_PATHS)
    return (
        "// SPDX-License-Identifier: MIT\n"
        "// Generated by tools/build_yosys_sources.py; do not edit by hand.\n"
        f"// Package-flattened synthesis view of {core_path.relative_to(ROOT)}.\n"
        f"{header}{separator}{bodies}\n{rest}"
    )


def write_output(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as output:
        output.write(content)
        temporary = Path(output.name)
    temporary.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[Path] = []
    for core_path, output_path in CORES.items():
        generated = render(core_path)
        if args.check:
            if not output_path.exists() or output_path.read_text(encoding="utf-8") != generated:
                stale.append(output_path)
        else:
            write_output(output_path, generated)
            print(f"wrote {output_path.relative_to(ROOT)}")
    if stale:
        for path in stale:
            print(f"stale Yosys source: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
