#!/usr/bin/env python3
"""Generate independent-model expectations for M6805-family RTL regressions."""

from __future__ import annotations

import argparse
from pathlib import Path

from model.common import Memory
from model.m6805 import FLAG_BITS, M6805Model, M6805State


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "sim" / "generated" / "m6805_opcode_vectors_pkg.sv"
TARGET_PC = 0x1005
ARCHITECTURES = ("m6805", "hd6305")


def fixture(architecture: str, opcode: int) -> M6805Model:
    memory = Memory()
    memory.load(TARGET_PC, [opcode, 0x10, 0x20, 0x30])
    for address in (0x0010, 0x0020, 0x0030, 0x0031, 0x1020, 0x1040):
        memory[address] = (address ^ 0xA6) & 0xFF
    # The RTL fixture also uses FFFE:FFFF as its reset vector. The final SWI
    # cycle reads FFFE as documented, although that data is architecturally
    # unused.
    memory.load(0xFFFA, [0x21, 0x00, 0x22, 0x00, 0x10, 0x00])
    for address, value in zip(range(0x0060, 0x0065), (0xE0, 0x12, 0x20, 0x10, 0x09), strict=True):
        memory[address] = value
    state = M6805State(a=0x12, x=0x20, sp=0x7F, pc=TARGET_PC, ccr=0)
    return M6805Model(architecture, memory=memory, state=state)


def collect(architecture: str) -> list[tuple[dict, M6805Model, object]]:
    template = M6805Model(architecture)
    vectors = []
    for record in template.spec["opcodes"]:
        if record["classification"] != "documented_instruction":
            continue
        model = fixture(architecture, record["opcode"])
        trace = model.step()
        vectors.append((record, model, trace))
    return vectors


def render_vector_function(lines: list[str], name: str, vectors: list[tuple]) -> None:
    lines.extend([
        f"  function automatic opcode_vector_t {name}_vector(input int unsigned vector_index);",
        "    begin", f"      {name}_vector = '0;", "      case (vector_index)",
    ])
    for index, (record, model, trace) in enumerate(vectors):
        undefined_mask = sum(1 << FLAG_BITS[flag] for flag in record["flags_undefined"])
        state = model.state
        prefix = f"          {name}_vector"
        lines.extend([
            f"        {index}: begin // {record['opcode_hex']} {record['mnemonic']}",
            f"{prefix}.opcode = 8'h{record['opcode']:02x};",
            f"{prefix}.cycles = 4'd{record['cycles']};",
            f"{prefix}.a = 8'h{state.a:02x};",
            f"{prefix}.x = 8'h{state.x:02x};",
            f"{prefix}.sp = 16'h{state.sp:04x};",
            f"{prefix}.pc = 16'h{state.pc:04x};",
            f"{prefix}.ccr = 5'h{state.ccr:02x};",
            f"{prefix}.ccr_mask = 5'h{(0x1F & ~undefined_mask):02x};",
            f"{prefix}.waiting_state = 1'b{int(state.waiting)};",
            f"{prefix}.stopped_state = 1'b{int(state.stopped)};",
            f"{prefix}.access_count = 4'd{len(trace.accesses)};",
            "        end",
        ])
    lines.extend(["        default: ;", "      endcase", "    end", "  endfunction", ""])


def render_access_function(lines: list[str], name: str, vectors: list[tuple]) -> None:
    lines.extend([
        f"  function automatic opcode_access_t {name}_access(",
        "    input logic [7:0] vector_index,", "    input logic [7:0] access_index", "  );",
        "    begin", f"      {name}_access = '0;", "      case ({vector_index, access_index})",
    ])
    for vector_index, (_record, _model, trace) in enumerate(vectors):
        for access_index, access in enumerate(trace.accesses):
            lines.extend([
                f"        16'h{vector_index:02x}{access_index:02x}: begin",
                f"          {name}_access.write_enable = 1'b{int(access.kind == 'write')};",
            ])
            if not access.data_defined:
                lines.append(f"          {name}_access.data_ignored = 1'b1;")
            lines.extend([
                f"          {name}_access.address_mask = 16'h{access.address_defined_mask:04x};",
                f"          {name}_access.address = 16'h{access.address:04x};",
                f"          {name}_access.data = 8'h{access.data:02x};",
                "        end",
            ])
    lines.extend(["        default: ;", "      endcase", "    end", "  endfunction", ""])


def render() -> str:
    vectors = {name: collect(name) for name in ARCHITECTURES}
    lines = [
        "// SPDX-License-Identifier: MIT",
        "// Generated by tools/build_m6805_rtl_vectors.py; do not edit by hand.",
        "package m6805_opcode_vectors_pkg;",
        *(f"  localparam int unsigned {name.upper()}_VECTOR_COUNT = {len(items)};" for name, items in vectors.items()),
        "  typedef struct packed {",
        "    logic [7:0] opcode;", "    logic [3:0] cycles;", "    logic [7:0] a;",
        "    logic [7:0] x;", "    logic [15:0] sp;", "    logic [15:0] pc;",
        "    logic [4:0] ccr;", "    logic [4:0] ccr_mask;",
        "    logic waiting_state;", "    logic stopped_state;", "    logic [3:0] access_count;",
        "  } opcode_vector_t;",
        "  typedef struct packed {", "    logic write_enable;", "    logic data_ignored;",
        "    logic [15:0] address_mask;",
        "    logic [15:0] address;",
        "    logic [7:0] data;", "  } opcode_access_t;", "",
    ]
    for name, items in vectors.items():
        render_vector_function(lines, name, items)
        render_access_function(lines, name, items)
    lines.extend(["endpackage", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"stale generated RTL vectors: run {Path(__file__).name}")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(generated, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
