#!/usr/bin/env python3
"""Generate independent-model expectations for M6800-family RTL regressions."""

from __future__ import annotations

import argparse
from pathlib import Path

from model.common import Memory
from model.m6800 import FLAG_BITS, M6800Model, M6800State


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "sim" / "generated" / "m6800_opcode_vectors_pkg.sv"
TARGET_PC = 0x100D
ARCHITECTURES = ("m6800", "m6801")


def fixture(architecture: str, opcode: int) -> M6800Model:
    memory = Memory()
    memory.load(TARGET_PC, [opcode, 0x10, 0x20, 0x30])
    for address in (0x0010, 0x0011, 0x0020, 0x0021, 0x1020, 0x1021, 0x2010, 0x2011):
        memory[address] = (address ^ 0x53) & 0xFF
    memory.load(0xFFFA, [0x30, 0x00, 0x31, 0x00, 0x32, 0x00])
    for offset, value in enumerate((0xC0, 0x34, 0x12, 0x20, 0x00, 0x10, 0x11), start=1):
        memory[0x4000 + offset] = value
    state = M6800State(a=0x12, b=0x34, x=0x2000, sp=0x4000, pc=TARGET_PC, ccr=0)
    return M6800Model(architecture, memory=memory, state=state)


def collect(architecture: str) -> list[tuple[dict, M6800Model, object]]:
    template = M6800Model(architecture)
    vectors = []
    for record in template.spec["opcodes"]:
        if record["classification"] != "documented_instruction":
            continue
        model = fixture(architecture, record["opcode"])
        trace = model.step()
        vectors.append((record, model, trace))
    return vectors


def render_vector_function(
    lines: list[str], architecture: str, vectors: list[tuple[dict, M6800Model, object]]
) -> None:
    lines.extend(
        [
            f"  function automatic opcode_vector_t {architecture}_vector(input int unsigned vector_index);",
            "    begin",
            f"      {architecture}_vector = '0;",
            "      case (vector_index)",
        ]
    )
    for index, (record, model, trace) in enumerate(vectors):
        undefined_mask = sum(1 << FLAG_BITS[flag] for flag in record["flags_undefined"])
        ccr_mask = 0x3F & ~undefined_mask
        state = model.state
        prefix = f"          {architecture}_vector"
        lines.extend(
            [
                f"        {index}: begin // {record['opcode_hex']} {record['mnemonic']}",
                f"{prefix}.opcode = 8'h{record['opcode']:02x};",
                f"{prefix}.cycles = 4'd{record['cycles']};",
                f"{prefix}.a = 8'h{state.a:02x};",
                f"{prefix}.b = 8'h{state.b:02x};",
                f"{prefix}.x = 16'h{state.x:04x};",
                f"{prefix}.sp = 16'h{state.sp:04x};",
                f"{prefix}.pc = 16'h{state.pc:04x};",
                f"{prefix}.ccr = 6'h{state.ccr:02x};",
                f"{prefix}.ccr_mask = 6'h{ccr_mask:02x};",
                f"{prefix}.waiting_state = 1'b{int(state.waiting)};",
                f"{prefix}.access_count = 4'd{len(trace.accesses)};",
                "        end",
            ]
        )
    lines.extend(["        default: ;", "      endcase", "    end", "  endfunction", ""])


def render_access_function(
    lines: list[str], architecture: str, vectors: list[tuple[dict, M6800Model, object]]
) -> None:
    lines.extend(
        [
            f"  function automatic opcode_access_t {architecture}_access(",
            "    input logic [7:0] vector_index,",
            "    input logic [7:0] access_index",
            "  );",
            "    begin",
            f"      {architecture}_access = '0;",
            "      case ({vector_index, access_index})",
        ]
    )
    for vector_index, (_record, _model, trace) in enumerate(vectors):
        for access_index, access in enumerate(trace.accesses):
            lines.extend(
                [
                    f"        16'h{vector_index:02x}{access_index:02x}: begin",
                    f"          {architecture}_access.write_enable = 1'b{int(access.kind == 'write')};",
                    f"          {architecture}_access.address = 16'h{access.address:04x};",
                    f"          {architecture}_access.data = 8'h{access.data:02x};",
                    "        end",
                ]
            )
    lines.extend(["        default: ;", "      endcase", "    end", "  endfunction", ""])


def render() -> str:
    all_vectors = {architecture: collect(architecture) for architecture in ARCHITECTURES}
    lines = [
        "// SPDX-License-Identifier: MIT",
        "// Generated by tools/build_m6800_rtl_vectors.py; do not edit by hand.",
        "package m6800_opcode_vectors_pkg;",
        *(f"  localparam int unsigned {name.upper()}_VECTOR_COUNT = {len(vectors)};" for name, vectors in all_vectors.items()),
        "  typedef struct packed {",
        "    logic [7:0] opcode;",
        "    logic [3:0] cycles;",
        "    logic [7:0] a;",
        "    logic [7:0] b;",
        "    logic [15:0] x;",
        "    logic [15:0] sp;",
        "    logic [15:0] pc;",
        "    logic [5:0] ccr;",
        "    logic [5:0] ccr_mask;",
        "    logic waiting_state;",
        "    logic [3:0] access_count;",
        "  } opcode_vector_t;",
        "  typedef struct packed {",
        "    logic write_enable;",
        "    logic [15:0] address;",
        "    logic [7:0] data;",
        "  } opcode_access_t;",
        "",
    ]
    for architecture, vectors in all_vectors.items():
        render_vector_function(lines, architecture, vectors)
        render_access_function(lines, architecture, vectors)
    lines.extend(["endpackage", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the committed artifact is stale")
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"stale generated RTL vectors: run {Path(__file__).name}")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(generated, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
