// SPDX-License-Identifier: MIT
// HD6303R normalized expanded-multiplexed Mode-2 integration.
//
// The Hitachi HD6301V1/HD6303R handbook identifies the HD6303R as the same
// die with mask ROM disabled and states that HD6301V1 information otherwise
// applies. Mode 2 supplies the documented internal register block and 128-byte
// RAM while leaving program memory and all vectors on the external bus.
module hd6303r_mcu (
  input  logic        clk_i,
  input  logic        reset_n_i,
  input  logic        clock_enable_i,
  input  logic        nmi_n_i,
  input  logic        irq1_n_i,
  input  logic        standby_power_ok_i,
  input  logic [7:0]  port1_i,
  input  logic [4:0]  port2_i,
  input  logic [7:0]  external_data_i,
  output logic [15:0] external_address_o,
  output logic [7:0]  external_data_o,
  output logic        external_write_o,
  output logic        external_bus_valid_o,
  output logic        external_opcode_fetch_o,
  output logic [7:0]  port1_o,
  output logic [7:0]  port1_oe_o,
  output logic [4:0]  port2_o,
  output logic [4:0]  port2_oe_o,
  output logic        sci_tx_o,
  output logic        sci_clock_o,
  output logic        timer_irq_o,
  output logic        sci_irq_o,
  output logic        opcode_fetch_o,
  output logic        retire_o,
  output logic        illegal_o,
  output logic        undefined_o,
  output logic        waiting_o,
  output logic        sleeping_o,
  output logic        interrupt_ack_o,
  output logic [15:0] debug_address_o,
  output logic [15:0] debug_pc_o,
  output logic [15:0] debug_sp_o,
  output logic [7:0]  debug_a_o,
  output logic [7:0]  debug_b_o,
  output logic [15:0] debug_x_o,
  output logic [5:0]  debug_ccr_o,
  output logic [15:0] debug_timer_o,
  output logic [15:0] debug_output_compare_o,
  output logic [15:0] debug_input_capture_o,
  output logic [7:0]  debug_tcsr_o,
  output logic [7:0]  debug_trcsr_o,
  output logic [7:0]  debug_receive_data_o,
  output logic [7:0]  debug_opcode_o
);
  mc6801_mcu #(
    .OPERATING_MODE(3'd2),
    .HITACHI_CPU(1'b1)
  ) device (
    .clk_i(clk_i),
    .reset_n_i(reset_n_i),
    .clock_enable_i(clock_enable_i),
    .nmi_n_i(nmi_n_i),
    .irq1_n_i(irq1_n_i),
    .standby_power_ok_i(standby_power_ok_i),
    .port1_i(port1_i),
    .port2_i(port2_i),
    .external_data_i(external_data_i),
    .external_address_o(external_address_o),
    .external_data_o(external_data_o),
    .external_write_o(external_write_o),
    .external_bus_valid_o(external_bus_valid_o),
    .external_opcode_fetch_o(external_opcode_fetch_o),
    .port1_o(port1_o),
    .port1_oe_o(port1_oe_o),
    .port2_o(port2_o),
    .port2_oe_o(port2_oe_o),
    .sci_tx_o(sci_tx_o),
    .sci_clock_o(sci_clock_o),
    .timer_irq_o(timer_irq_o),
    .sci_irq_o(sci_irq_o),
    .opcode_fetch_o(opcode_fetch_o),
    .retire_o(retire_o),
    .illegal_o(illegal_o),
    .undefined_o(undefined_o),
    .waiting_o(waiting_o),
    .sleeping_o(sleeping_o),
    .interrupt_ack_o(interrupt_ack_o),
    .debug_address_o(debug_address_o),
    .debug_pc_o(debug_pc_o),
    .debug_sp_o(debug_sp_o),
    .debug_a_o(debug_a_o),
    .debug_b_o(debug_b_o),
    .debug_x_o(debug_x_o),
    .debug_ccr_o(debug_ccr_o),
    .debug_timer_o(debug_timer_o),
    .debug_output_compare_o(debug_output_compare_o),
    .debug_input_capture_o(debug_input_capture_o),
    .debug_tcsr_o(debug_tcsr_o),
    .debug_trcsr_o(debug_trcsr_o),
    .debug_receive_data_o(debug_receive_data_o),
    .debug_opcode_o(debug_opcode_o)
  );
endmodule
